include:
  - ./django-main/compose.yml
  - ./django-soft/compose.yml
  - ./nginx/compose.yml
  - ./rocket-ecommerce/compose.yml
  - ./website/compose.yml
  - ./netdata/compose.yml
  - ./db/compose.yml

