# Generated by Django 4.2.8 on 2024-09-26 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_name", models.CharField(max_length=255)),
                ("model_name", models.CharField(max_length=255)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[("BAR", "Bar"), ("LINE", "Line")], max_length=50
                    ),
                ),
                ("props", models.JSONField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChartsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("BAR", "Bar"), ("LINE", "Line")], max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("prop1", models.CharField(blank=True, max_length=50, null=True)),
                ("prop1_label", models.CharField(blank=True, max_length=50, null=True)),
                ("prop1_q", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "prop1_filters",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "prop1_values",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("prop2", models.CharField(blank=True, max_length=50, null=True)),
                ("prop2_label", models.CharField(blank=True, max_length=50, null=True)),
                ("prop2_q", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "prop2_filters",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "prop2_values",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("prop3", models.CharField(blank=True, max_length=50, null=True)),
                ("prop3_label", models.CharField(blank=True, max_length=50, null=True)),
                ("prop3_q", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "prop3_filters",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "prop3_values",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("prop4", models.CharField(blank=True, max_length=50, null=True)),
                ("prop4_label", models.CharField(blank=True, max_length=50, null=True)),
                ("prop4_q", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "prop4_filters",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "prop4_values",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("prop5", models.CharField(blank=True, max_length=50, null=True)),
                ("prop5_label", models.CharField(blank=True, max_length=50, null=True)),
                ("prop5_q", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "prop5_filters",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "prop5_values",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("prop6", models.CharField(blank=True, max_length=50, null=True)),
                ("prop6_label", models.CharField(blank=True, max_length=50, null=True)),
                ("prop6_q", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "prop6_filters",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "prop6_values",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("prop7", models.CharField(blank=True, max_length=50, null=True)),
                ("prop7_label", models.CharField(blank=True, max_length=50, null=True)),
                ("prop7_q", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "prop7_filters",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "prop7_values",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("prop8", models.CharField(blank=True, max_length=50, null=True)),
                ("prop8_label", models.CharField(blank=True, max_length=50, null=True)),
                ("prop8_q", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "prop8_filters",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "prop8_values",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
