# Generated by Django 4.2.8 on 2024-09-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_dyn_charts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chart",
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="type",
            field=models.CharField(
                choices=[
                    ("BAR", "Bar"),
                    ("LINE", "Line"),
                    ("PIE", "Pie"),
                    ("DONUT", "Donut"),
                ],
                max_length=50,
            ),
        ),
    ]
