# Generated by Django 4.1.12 on 2024-09-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_dyn_charts", "0002_delete_chart_alter_chartsconfig_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chartsconfig",
            name="type",
            field=models.CharField(
                choices=[
                    ("BAR", "Bar"),
                    ("LINE", "Line"),
                    ("AREA", "Area"),
                    ("COLUMN", "Column"),
                    ("PIE", "Pie"),
                    ("DONUT", "Donut"),
                    ("RADIAL", "Radial"),
                    ("RADAR", "Radar"),
                    ("POLAR", "Polar"),
                    ("GAUGE", "Gauge"),
                    ("GAUGE_STROKED", "Gauge_Stroked"),
                ],
                max_length=50,
            ),
        ),
    ]
