# Generated by Django 4.1.12 on 2024-10-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_dyn_charts", "0003_alter_chartsconfig_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartsconfig",
            name="errInfo",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="chartsconfig",
            name="status",
            field=models.IntegerField(default=-1),
        ),
    ]
