# Generated by Django 4.1.12 on 2024-10-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_dyn_charts", "0004_chartsconfig_errinfo_chartsconfig_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chartsconfig",
            name="app",
        ),
    ]
