# Generated by Django 4.1.12 on 2024-10-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_dyn_charts", "0006_remove_chartsconfig_prop7_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chartsconfig",
            name="description",
        ),
    ]
