# Generated by Django 4.1.12 on 2024-10-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_dyn_charts", "0007_remove_chartsconfig_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartsconfig",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
