# Generated by Django 4.1.12 on 2024-10-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_dyn_charts", "0008_chartsconfig_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop1_filters",
            field=models.CharField(
                blank=True,
                choices=[
                    ("x-axis", "x-axis"),
                    ("upercase", "upercase"),
                    ("lowercase", "lowercase"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop1_q",
            field=models.CharField(
                blank=True,
                choices=[("x-axis", "x-axis"), ("xy-axis", "y-axis")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop2_filters",
            field=models.CharField(
                blank=True,
                choices=[
                    ("x-axis", "x-axis"),
                    ("upercase", "upercase"),
                    ("lowercase", "lowercase"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop2_q",
            field=models.CharField(
                blank=True,
                choices=[("x-axis", "x-axis"), ("xy-axis", "y-axis")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop3_filters",
            field=models.CharField(
                blank=True,
                choices=[
                    ("x-axis", "x-axis"),
                    ("upercase", "upercase"),
                    ("lowercase", "lowercase"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop3_q",
            field=models.CharField(
                blank=True,
                choices=[("x-axis", "x-axis"), ("xy-axis", "y-axis")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop4_filters",
            field=models.CharField(
                blank=True,
                choices=[
                    ("x-axis", "x-axis"),
                    ("upercase", "upercase"),
                    ("lowercase", "lowercase"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop4_q",
            field=models.CharField(
                blank=True,
                choices=[("x-axis", "x-axis"), ("xy-axis", "y-axis")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop5_filters",
            field=models.CharField(
                blank=True,
                choices=[
                    ("x-axis", "x-axis"),
                    ("upercase", "upercase"),
                    ("lowercase", "lowercase"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop5_q",
            field=models.CharField(
                blank=True,
                choices=[("x-axis", "x-axis"), ("xy-axis", "y-axis")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop6_filters",
            field=models.CharField(
                blank=True,
                choices=[
                    ("x-axis", "x-axis"),
                    ("upercase", "upercase"),
                    ("lowercase", "lowercase"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop6_q",
            field=models.CharField(
                blank=True,
                choices=[("x-axis", "x-axis"), ("xy-axis", "y-axis")],
                max_length=50,
                null=True,
            ),
        ),
    ]
