# Generated by Django 4.1.12 on 2024-10-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_dyn_charts", "0009_alter_chartsconfig_prop1_filters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop1_filters",
            field=models.CharField(
                blank=True,
                choices=[
                    ("date_format", "date_format"),
                    ("upercase", "upercase"),
                    ("lowercase", "lowercase"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop2_filters",
            field=models.CharField(
                blank=True,
                choices=[
                    ("date_format", "date_format"),
                    ("upercase", "upercase"),
                    ("lowercase", "lowercase"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop3_filters",
            field=models.CharField(
                blank=True,
                choices=[
                    ("date_format", "date_format"),
                    ("upercase", "upercase"),
                    ("lowercase", "lowercase"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop4_filters",
            field=models.CharField(
                blank=True,
                choices=[
                    ("date_format", "date_format"),
                    ("upercase", "upercase"),
                    ("lowercase", "lowercase"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop5_filters",
            field=models.CharField(
                blank=True,
                choices=[
                    ("date_format", "date_format"),
                    ("upercase", "upercase"),
                    ("lowercase", "lowercase"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop6_filters",
            field=models.CharField(
                blank=True,
                choices=[
                    ("date_format", "date_format"),
                    ("upercase", "upercase"),
                    ("lowercase", "lowercase"),
                ],
                max_length=128,
                null=True,
            ),
        ),
    ]
