# Generated by Django 4.1.12 on 2024-10-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_dyn_charts", "0005_remove_chartsconfig_app"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop7",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop7_filters",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop7_label",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop7_q",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop7_values",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop8",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop8_filters",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop8_label",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop8_q",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop8_values",
        ),
        migrations.AddField(
            model_name="chartsconfig",
            name="title",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
