# Generated by Django 4.1.12 on 2024-10-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_dyn_charts", "0010_alter_chartsconfig_prop1_filters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop1_q",
            field=models.CharField(
                blank=True,
                choices=[
                    ("x-axis", "x-axis"),
                    ("y-axis", "y-axis"),
                    ("sum", "sum"),
                    ("count", "count"),
                    ("avg", "avg"),
                    ("min", "min"),
                    ("max", "max"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop2_q",
            field=models.CharField(
                blank=True,
                choices=[
                    ("x-axis", "x-axis"),
                    ("y-axis", "y-axis"),
                    ("sum", "sum"),
                    ("count", "count"),
                    ("avg", "avg"),
                    ("min", "min"),
                    ("max", "max"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop3_q",
            field=models.CharField(
                blank=True,
                choices=[
                    ("x-axis", "x-axis"),
                    ("y-axis", "y-axis"),
                    ("sum", "sum"),
                    ("count", "count"),
                    ("avg", "avg"),
                    ("min", "min"),
                    ("max", "max"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop4_q",
            field=models.CharField(
                blank=True,
                choices=[
                    ("x-axis", "x-axis"),
                    ("y-axis", "y-axis"),
                    ("sum", "sum"),
                    ("count", "count"),
                    ("avg", "avg"),
                    ("min", "min"),
                    ("max", "max"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop5_q",
            field=models.CharField(
                blank=True,
                choices=[
                    ("x-axis", "x-axis"),
                    ("y-axis", "y-axis"),
                    ("sum", "sum"),
                    ("count", "count"),
                    ("avg", "avg"),
                    ("min", "min"),
                    ("max", "max"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop6_q",
            field=models.CharField(
                blank=True,
                choices=[
                    ("x-axis", "x-axis"),
                    ("y-axis", "y-axis"),
                    ("sum", "sum"),
                    ("count", "count"),
                    ("avg", "avg"),
                    ("min", "min"),
                    ("max", "max"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
