# Generated by Django 4.1.12 on 2024-10-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_dyn_charts", "0011_alter_chartsconfig_prop1_q_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chartsconfig",
            old_name="model",
            new_name="model_name",
        ),
    ]
