# Generated by Django 4.1.12 on 2024-10-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_dyn_charts", "0012_rename_model_chartsconfig_model_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop3",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop3_filters",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop3_label",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop3_q",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop3_values",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop4",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop4_filters",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop4_label",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop4_q",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop4_values",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop5",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop5_filters",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop5_label",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop5_q",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop5_values",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop6",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop6_filters",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop6_label",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop6_q",
        ),
        migrations.RemoveField(
            model_name="chartsconfig",
            name="prop6_values",
        ),
    ]
