# Generated by Django 4.1.12 on 2024-10-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_dyn_charts", "0013_remove_chartsconfig_prop3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop1_q",
            field=models.CharField(
                blank=True,
                choices=[
                    ("x-axis", "x-axis"),
                    ("y-axis", "y-axis"),
                    ("sum", "sum"),
                    ("count", "count"),
                    ("avg", "avg"),
                    ("min", "min"),
                    ("max", "max"),
                ],
                default="x-axis",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartsconfig",
            name="prop2_q",
            field=models.CharField(
                blank=True,
                choices=[
                    ("x-axis", "x-axis"),
                    ("y-axis", "y-axis"),
                    ("sum", "sum"),
                    ("count", "count"),
                    ("avg", "avg"),
                    ("min", "min"),
                    ("max", "max"),
                ],
                default="y-axis",
                max_length=50,
                null=True,
            ),
        ),
    ]
