services:
  rocket-ecommerce:
    container_name: rocket-ecommerce-BV-19-06-2026
    image: peti0u/final-tp:rocket-ecommerce-bv-19-06-2026
    restart: always
    env_file:
      - .env
    networks:
      - app_net
    healthcheck:
      test: "wget http://localhost:5005"
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app_net:
    external: true