services:
  rocket-ecommerce:
    container_name: rocket-ecommerce-BV-19-06-2026
    build: .
    image: rocket-ecommerce-bv-19-06-2026
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy