services:
  nginx:
      container_name: nginx-BV-19-06-2026
      build: "."
      image: nginx-bv-19-06-2026
      restart: always
      ports:
        - "5000:5000"
        - "5001:5001"
      depends_on:
        rocket-ecommerce:
          condition: service_healthy
        db:
          condition: service_healthy

      networks:
        - app_net

networks:
  app_net:
    external: true