upstream django-main {
    server django-main:5005;
}

server {
    listen 5000;
    server_name localhost;

    location / {
        proxy_pass http://django-main;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

###########################################################

upstream rocket-ecommerce {
    server rocket-ecommerce:5005;
}

server {
    listen 5001;
    server_name localhost;

    location / {
        proxy_pass http://rocket-ecommerce;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

###########################################################