services:
  db:
    image: mysql:8.0
    container_name: db-BV-19-06-2026
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2026
      MYSQL_DATABASE: Wearo
      MYSQL_USER: wearo
      MYSQL_PASSWORD: 2026
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
        - app_net

networks:
  app_net:
    external: true

volumes:
  db_data:
