# Generated by Django 4.1.12 on 2024-10-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_dyn_dt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hideshowfilter",
            name="parent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="modelfilter",
            name="parent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pageitems",
            name="parent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
