# Generated by Django 4.2.8 on 2024-09-26 05:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("info", models.CharField(default="", max_length=100)),
                ("price", models.IntegerField(blank=True, default=99, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "buyerEmail",
                    models.EmailField(
                        blank=True, default="fake@sales.com", max_length=254, null=True
                    ),
                ),
                (
                    "purchaseDate",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("country", models.TextField(blank=True, default="USA", null=True)),
                (
                    "refunded",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")],
                        default="NO",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("EUR", "EUR")],
                        default="USD",
                        max_length=10,
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.product"
                    ),
                ),
            ],
        ),
    ]
