# Generated by Django 4.1.12 on 2024-10-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_salesgumroad"),
    ]

    operations = [
        migrations.CreateModel(
            name="Titanic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("PassengerId", models.IntegerField(blank=True, null=True)),
                ("Survived", models.IntegerField(blank=True, null=True)),
                ("Pclass", models.IntegerField(blank=True, null=True)),
                ("Name", models.TextField(blank=True, null=True)),
                ("Sex", models.TextField(blank=True, null=True)),
                ("Age", models.FloatField(blank=True, null=True)),
                ("SibSp", models.IntegerField(blank=True, null=True)),
                ("Parch", models.IntegerField(blank=True, null=True)),
                ("Ticket", models.TextField(blank=True, null=True)),
                ("Fare", models.FloatField(blank=True, null=True)),
                ("Cabin", models.TextField(blank=True, null=True)),
                ("Embarked", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
