# Generated by Django 4.1.12 on 2024-10-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_titanic"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SalesGumroad",
        ),
    ]
